### ISSUE TITLE
From `wordpress` to `wordpress-core`

### ISSUE THREAD

**Issue by rask** [johnpbloch/wordpress-core#1]
Just chimed in to clarify whether this repo/package change is permanent and we should switch from `johnpbloch/wordpress` to `johnpbloch/wordpress-core` in our `composer.json` requirements?

**Comment by djvdorp** [comment]
+1

**Comment by johnpbloch** [comment]
Yes, this change is permanent. The `johnpbloch/wordpress` package will almost definitely always exist though, since it's a nice convenience if you need both core and the core installer.

If you do change `johnpbloch/wordpress` to `johnpbloch/wordpress-core`, make sure you also add `johnpbloch/wordpress-core-installer` as well.

**Comment by rask** [comment]
@johnpbloch I have been doing that now and works well. There were some issues with the combining package `wordpress` which includes core and installer on our end. Need to try again in some time. Thanks!
