### ISSUE TITLE
Call to undefined function get_home_path()

### ISSUE THREAD

**Issue by philopen** [johnpbloch/wordpress-core#13]
Fatal error with version 4.9.6 : Call to undefined function get_home_path()

There is a problem for all my wordpress sites.
I use composer with Bedrock and I have to rollback to your version 4.9.5.

Please fix this bug

**Comment by philopen** [comment]
It seems that this bug is about the new version of wordpress 4.9.6.

**Comment by daggemarren** [comment]
I have this problem on my multisite with version 4.9.8.

**Comment by johnpbloch** [comment]
Hi @daggemarren,
Thanks for stopping by. Since this repository is programmatically generated by downloading WordPress core source code, this is a problem with core itself or one of your plugins or theme. I'd encourage you to isolate the problem by trying to reproduce the problem with all plugins inactive and using the default theme. If you can reproduce it, it's a bug in core and should be filed at https://core.trac.wordpress.org. If not, start activating plugins one-by-one and testing after each one. If you see the error again, it's being caused by the plugin you just activated and you can file a bug with that plugin's author. Finally, if none of your plugins cause the error, it's probably your theme. Switch back to it and verify, then file a bug with the theme author.
