### ISSUE TITLE
Twenty Nineteen missing

### ISSUE THREAD

**Issue by swissspidy** [johnpbloch/wordpress-core#16]
Twenty Nineteen has been added to the WordPress core svn repository a while back and is available in the 5.0 branch there.

However, it is missing here in this repository: https://github.com/johnpbloch/wordpress-core/tree/5.0/wp-content/themes

**Comment by johnpbloch** [comment]
@swissspidy As @alpipego pointed out in #17 this is probably due to the fact that the 5.0 branch hasn't synced in a month. I'm going to close this, since I'm confident that resolving the larger issue will fix this one as well. If that's not the case, I'll re-open at that time. Thanks for your patience.
