### ISSUE TITLE
Alpha releases since 5.1 

### ISSUE THREAD

**Issue by alpipego** [johnpbloch/wordpress-core#18]
Since the 5.1 version there are a lot of alpha and beta builds marked as releases:

![image](https://user-images.githubusercontent.com/2003667/52861453-124ced00-3165-11e9-89c3-a9dd1f228b99.png)

Is this something that can (and should) be controlled from this repository?

**Comment by johnpbloch** [comment]
Hi @alpipego, thanks for coming by to bring that up. That's definitely neither intended, nor desirable. I'm a little too busy right now to take care of this, but it looks like the code in https://github.com/johnpbloch/build-wp isn't sufficiently guarded against that behavior. It's supposed to build actual pre-release tags for the various release milestones (e.g. beta1 beta2, rc1, rc2, etc.), but it's clearly not working that way. If you're so inclined, I'd happily accept a PR on that repo to address the issue and keep it from happening in the future, but that's a bit low on my list of priorities at the moment.

Again, thank you for letting me know. I appreciate the feedback.

**Comment by Seldaek** [comment]
@johnpbloch your package is generating a ton of packagist.org update jobs (I suppose your bot is pushing syncs very often). It'd be great if you could do the following to reduce the impact a little bit:

- clean up alpha/.. tags if possible (what this issue is about)
- avoid pushing if nothing changed, as every push triggers an update and then we have to go through all tags/branches to see if anything changed
- if possible, get rid of tags/branches that don't have a composer.json, as we have to fetch those repeatedly to make sure there isn't a composer.json still.. that's the list of the 339 of them: `clean, tag-1.5, tag-1.5.1, tag-1.5.1.1, tag-1.5.1.2, tag-1.5.1.3, tag-1.5.2, tag-2.0, tag-2.0.1, tag-2.0.2, tag-2.0.3, tag-2.0.4, tag-2.0.5, tag-2.0.6, tag-2.0.7, tag-2.0.8, tag-2.0.9, tag-2.0.10, tag-2.0.11, tag-2.1, tag-2.1.1, tag-2.1.2, tag-2.1.3, tag-2.2, tag-2.2.1, tag-2.2.2, tag-2.2.3, tag-2.3, tag-2.3.1, tag-2.3.2, tag-2.3.3, tag-2.5, tag-2.5.1, tag-2.6, tag-2.6.1, tag-2.6.2, tag-2.6.3, tag-2.6.5, tag-2.7, tag-2.7.1, tag-2.8, tag-2.8.1, tag-2.8.2, tag-2.8.3, tag-2.8.4, tag-2.8.5, tag-2.8.6, tag-2.9, tag-2.9.1, tag-2.9.2, tag-3.0, tag-3.0.1, tag-3.0.2, tag-3.0.3, tag-3.0.4, tag-3.0.5, tag-3.0.6, tag-3.1, tag-3.1.1, tag-3.1.2, tag-3.1.3, tag-3.1.4, tag-3.2, tag-3.2.1, tag-3.3, tag-3.3.1, tag-3.3.2, tag-3.3.3, tag-3.4, tag-3.4.1, tag-3.4.2, tag-3.5, tag-3.5.1, tag-3.5.2, tag-3.6, tag-3.6.1, tag-3.7, tag-3.7.1, tag-3.7.2, tag-3.7.3, tag-3.7.4, tag-3.7.5, tag-3.7.6, tag-3.7.7, tag-3.7.8, tag-3.7.9, tag-3.7.10, tag-3.7.11, tag-3.7.12, tag-3.7.13, tag-3.7.14, tag-3.7.15, tag-3.7.16, tag-3.7.17, tag-3.7.18, tag-3.7.19, tag-3.7.20, tag-3.7.21, tag-3.7.22, tag-3.7.23, tag-3.7.24, tag-3.7.25, tag-3.7.26, tag-3.7.27, tag-3.7.28, tag-3.8, tag-3.8.1, tag-3.8.2, tag-3.8.3, tag-3.8.4, tag-3.8.5, tag-3.8.6, tag-3.8.7, tag-3.8.8, tag-3.8.9, tag-3.8.10, tag-3.8.11, tag-3.8.12, tag-3.8.13, tag-3.8.14, tag-3.8.15, tag-3.8.16, tag-3.8.17, tag-3.8.18, tag-3.8.19, tag-3.8.20, tag-3.8.21, tag-3.8.22, tag-3.8.23, tag-3.8.24, tag-3.8.25, tag-3.8.26, tag-3.8.27, tag-3.8.28, tag-3.9, tag-3.9.1, tag-3.9.2, tag-3.9.3, tag-3.9.4, tag-3.9.5, tag-3.9.6, tag-3.9.7, tag-3.9.8, tag-3.9.9, tag-3.9.10, tag-3.9.11, tag-3.9.12, tag-3.9.13, tag-3.9.14, tag-3.9.15, tag-3.9.16, tag-3.9.17, tag-3.9.18, tag-3.9.19, tag-3.9.20, tag-3.9.21, tag-3.9.22, tag-3.9.23, tag-3.9.24, tag-3.9.25, tag-3.9.26, tag-4.0, tag-4.0.1, tag-4.0.2, tag-4.0.3, tag-4.0.4, tag-4.0.5, tag-4.0.6, tag-4.0.7, tag-4.0.8, tag-4.0.9, tag-4.0.10, tag-4.0.11, tag-4.0.12, tag-4.0.13, tag-4.0.14, tag-4.0.15, tag-4.0.16, tag-4.0.17, tag-4.0.18, tag-4.0.19, tag-4.0.20, tag-4.0.21, tag-4.0.22, tag-4.0.23, tag-4.0.24, tag-4.0.25, tag-4.1, tag-4.1.1, tag-4.1.2, tag-4.1.3, tag-4.1.4, tag-4.1.5, tag-4.1.6, tag-4.1.7, tag-4.1.8, tag-4.1.9, tag-4.1.10, tag-4.1.11, tag-4.1.12, tag-4.1.13, tag-4.1.14, tag-4.1.15, tag-4.1.16, tag-4.1.17, tag-4.1.18, tag-4.1.19, tag-4.1.20, tag-4.1.21, tag-4.1.22, tag-4.1.23, tag-4.1.24, tag-4.1.25, tag-4.2, tag-4.2.1, tag-4.2.2, tag-4.2.3, tag-4.2.4, tag-4.2.5, tag-4.2.6, tag-4.2.7, tag-4.2.8, tag-4.2.9, tag-4.2.10, tag-4.2.11, tag-4.2.12, tag-4.2.13, tag-4.2.14, tag-4.2.15, tag-4.2.16, tag-4.2.17, tag-4.2.18, tag-4.2.19, tag-4.2.20, tag-4.2.21, tag-4.2.22, tag-4.3, tag-4.3.1, tag-4.3.2, tag-4.3.3, tag-4.3.4, tag-4.3.5, tag-4.3.6, tag-4.3.7, tag-4.3.8, tag-4.3.9, tag-4.3.10, tag-4.3.11, tag-4.3.12, tag-4.3.13, tag-4.3.14, tag-4.3.15, tag-4.3.16, tag-4.3.17, tag-4.3.18, tag-4.4, tag-4.4.1, tag-4.4.2, tag-4.4.3, tag-4.4.4, tag-4.4.5, tag-4.4.6, tag-4.4.7, tag-4.4.8, tag-4.4.9, tag-4.4.10, tag-4.4.11, tag-4.4.12, tag-4.4.13, tag-4.4.14, tag-4.4.15, tag-4.4.16, tag-4.4.17, tag-4.5, tag-4.5.1, tag-4.5.2, tag-4.5.3, tag-4.5.4, tag-4.5.5, tag-4.5.6, tag-4.5.7, tag-4.5.8, tag-4.5.9, tag-4.5.10, tag-4.5.11, tag-4.5.12, tag-4.5.13, tag-4.5.14, tag-4.5.15, tag-4.5.16, tag-4.6, tag-4.6.1, tag-4.6.2, tag-4.6.3, tag-4.6.4, tag-4.6.5, tag-4.6.6, tag-4.6.7, tag-4.6.8, tag-4.6.9, tag-4.6.10, tag-4.6.11, tag-4.6.12, tag-4.6.13, tag-4.7, tag-4.7.1, tag-4.7.2, tag-4.7.3, tag-4.7.5, tag-4.7.6, tag-4.7.7, tag-4.7.8, tag-4.7.9, tag-4.7.10, tag-4.7.11, tag-4.7.12, tag-4.8, tag-4.8.1, tag-4.8.2, tag-4.8.3, tag-4.8.4, tag-4.8.5, tag-4.8.6, tag-4.8.7, tag-4.8.8, tag-4.9, tag-4.9.1, tag-4.9.2, tag-4.9.3, tag-4.9.4, tag-4.9.5, tag-4.9.6, tag-4.9.7, tag-4.9.8, tag-4.9.9, tag-5.0, tag-5.0.1, tag-5.0.2, tag-5.0.3`

Our CPU resources would be very appreciative ;)

**Comment by johnpbloch** [comment]
@Seldaek 
![I am ashamed](https://jbl.me/ashamed)
I'll take some time take care of these.

**Comment by Seldaek** [comment]
Thanks, it's not super urgent but I wanted to raise the point because your package is by far the one doing the most updates at the moment.

**Comment by johnpbloch** [comment]
Closing this issue as I've removed the tags and releases from github and packagist. I'll be working on https://github.com/johnpbloch/build-wp to prevent future non-release tags in the future as well as shore up the build process in general.

**Comment by Seldaek** [comment]
@johnpbloch thanks! That helps already a bit, but what would be even better is if you can get rid of the "build" branches https://github.com/johnpbloch/wordpress-core/branches all these named `tag-*`. I suspect they don't really need to be pushed ever.
