### ISSUE TITLE
Release 4.8.3

### ISSUE THREAD

**Issue by franzliedke** [johnpbloch/wordpress-core#9]
This version contains critical bug fixes:
- https://blog.ircmaxell.com/2017/10/disclosure-wordpress-wpdb-sql-injection-technical.html
- https://blog.ircmaxell.com/2017/10/disclosure-wordpress-wpdb-sql-injection-background.html

Please release the new version as quickly as possible.

**Comment by johnpbloch** [comment]
Already working on it. Thanks for stopping by.

**Comment by franzliedke** [comment]
Awesome, thanks!

And sorry for the stress. I didn't realize the release was that fresh...

**Comment by johnpbloch** [comment]
Don't worry, there was no added stress. Ordinarily these are automated and will generally roll out within an hour (the update script runs every 15 minutes, but sometimes it takes a while to get to the tagged releases, since it starts with trunk, then dev branches first). As it turns out, my build server had run out of storage anyway. If I hadn't happened to look into the update already, I would have needed somebody to tell me that the update hadn't happened yet.

New versions are starting to roll in now, so I'll go ahead and close this. Again, thanks for checking in. :)
